spring:
  application:
    name: guardians-gate

  config:
    import: optional:file:../.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/stronghold_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
